arista_nodes:
  children:
    isp:
      hosts:
        isp1:
          ansible_host: 172.20.20.10
    edge:
      hosts:
        edge1:
          ansible_host: 172.20.20.20
    core:
      hosts:
        core1:
          ansible_host: 172.20.20.30      
        core2:
          ansible_host: 172.20.20.40  
    access:
      hosts:
        access1:
          ansible_host: 172.20.20.50
        access2:
          ansible_host: 172.20.20.60


vars:
  ansible_user: admin
  ansible_password: admin
  ansible_network_os: arista.eos.eos
  ansible_connection: network_cli
  ansible_become: true
  ansible_become_method: enable